name: Question
description: Ask about usage, behavior, or design
title: '[Question]: '
labels: ['question']
assignees: []

body:
  - type: textarea
    id: question
    attributes:
      label: What's your question?
      placeholder: Be clear and specific so we can help!
    validations:
      required: true
